# Generated by Django 4.1.3 on 2022-11-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watson", "0002_alter_searchentry_object_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="searchentry",
            name="meta_encoded",
        ),
        migrations.AddField(
            model_name="searchentry",
            name="meta",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
